version: '3.7'

services:
  # Сервис для Django-приложения
  web:
    build:
      context: .  # Путь к директории с Dockerfile (текущая директория)
    ports:
      - "9999:9999"  # Прокидываем порт хоста на порт контейнера
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
    depends_on:
      - redis  # Зависимость от контейнера с Redis

  # Сервис для Redis
  redis:
    image: redis:latest  # Используем официальный образ Redis
